import { useSession, signOut } from "next-auth/react"
import Head from "next/head"
import { useRouter } from "next/router";
import { PropsWithChildren, ReactElement, useEffect } from "react"

export function Layout({ children }: PropsWithChildren): ReactElement {
  const { data: sessionData } = useSession()
  const router = useRouter();

  useEffect(() => {
    if(sessionData?.user?.id) {
        router.replace('/user/goals');
    } else {
        router.replace('/auth/signin');
    }
  }, [sessionData])

    if(!sessionData && router.pathname.includes('user')) return <p>Loading...</p>

    return (
        <>
        <Head>
            <title>Create T3 App</title>
            <meta name="description" content="Generated by create-t3-app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="w-screen h-screen bg-slate-50 dark:bg-slate-800">
            <main className="m-auto max-w-md w-screen flex flex-col items-center justify-center">
            <header className="self-end">
                {sessionData && (
                    <button
                        className="font-bold text-slate-800 dark:text-white "
                        onClick={() => signOut()}
                    >
                        Sign out
                    </button>
                )}
            </header>
                {children}
            </main>
        </div>
        </>
    )
}
