import { useSession, signOut, signIn } from "next-auth/react"
import Head from "next/head"
import { useRouter } from "next/router";
import { PropsWithChildren, ReactElement, useEffect, useMemo } from "react"

export function Layout({ children }: PropsWithChildren): ReactElement {
  const { data: sessionData } = useSession()
  const router = useRouter();

  useEffect(() => {
    if(sessionData?.user?.id) {
        router.replace('/user/goals');
    } else {
        router.replace('/');
    }
  }, [sessionData])

    if(!sessionData && router.pathname.includes('user')) {
        return (
            <>
                <p>Loading...</p>
            </>
        )
    }

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header>
                <button
                    className="font-bold text-black"
                    onClick={sessionData ? () => signOut() : () => signIn()}
                >
                    {sessionData ? "Sign out" : "Sign in"}
                </button>
            </header>
            <main className="w-screen flex items-center justify-center">{children}</main>
        </>
    )
}